<h1 align="center">Précisions et consignes pour une consultation efficace</h1>
        
		<h2>Etat des lieux du bassin Rhône-Méditerranée 2019<br />
Consultation sur le niveau d'impact des pressions sur les masses d'eau</h2>
<ol>
	<li><b>La masse d'eau</b> est l'unité spatiale pour identifier les mesures à conduire pour atteindre des objectifs de bon état des eaux définis par la directive cadre sur l'eau. De quelques km à quelques dizaines de km pour les cours d'eau et eaux côtières, de quelques dizaines d'hectares à quelques dizaines de Km² pour les plans d'eau et lagunes, et de plusieurs dizaines de Km² pour les eaux souterraines. Cette unité est désormais couramment utilisée par les acteurs. 
		<ul><li><b>Les avis demandés doivent reposer sur des appréciations (1) des impacts des activités humaines à l'échelle de la taille des masses d'eau (sans considérer les impacts très localisés)  et (2) des pressions sur lesquelles agir pour restaurer l'état des eaux à ces échelles.</b></li></ul></li>
	<li><b>Les impacts</b> qualifient l'incidence des pressions humaines sur chaque masse d'eau. Leur évaluation sert à identifier les pressions qui peuvent empêcher d'atteindre le bon état. L'estimation de ces  impacts a été réalisée avec des données de la surveillance des milieux (qualité et quantité) du bassin, des études locales et de données sur les pressions issues d'outils et méthodes nationaux ou de bassin. Elle possède une validité statistique fondée sur des chroniques de données pluriannuelles et des approches modélisées adaptées à l'échelle et au contexte du bassin. Elle n'a pas pour objet de rendre compte des hétérogénéités locales mais au contraire de faire ressortir les situations contrastées entre les masses d'eau. Leur expertise par les acteurs consultés demande une connaissance de l'étendue des secteurs dégradés ou menacés, des points de pollution ou obstacles majeurs … ainsi que, le cas échéant, une expertise des effets des travaux réalisés, en application des programmes de mesures des SDAGE 2010-2015 et 2016-2021. 
		<ul><li><b>Il est demandé d'apprécier, à dire d'expert, les niveaux d'impacts proposées (1-faible ;           2-moyen ; 3-fort), en les comparant à la connaissance de la situation des masses d'eau par les acteurs de terrain. Il n'est pas attendu de procéder à une vérification des données et des méthodes utilisées pour produire les évaluations proposées.</b></li>
		<li><b>Les demandes d'ajustement des impacts devront être fondées sur une connaissance actuelle de la dimension des problèmes rencontrés (ex : ordres de grandeur des linéaires ou superficies concernées).</b></li></ul></li>
	<li><b>Les pressions à l'origine du risque de non-atteinte des objectifs environnementaux</b> subies par chaque masse d'eau sont celles dont l'effet est significatif par rapport à la taille de la masse d'eau, seule (pression dont l'impact est jugé fort) ou en association avec d'autres pressions (combinaison de plusieurs pressions dont l'impact individuel est moyen) pour être à l'origine d'une dégradation actuelle ou d'une menace de dégradation à un horizon proche (« pressions importantes »). Le travail de co-construction du programme de mesures portera sur ces pressions.
		<ul><li><b>Les demandes de modification des pressions à l'origine du risque de non-atteinte des objectifs environnementaux devront être justifiées par un ou des ajustements des impacts de ces pressions.</b></li></ul></li>
</ol>
<p><b>Les zonages pré-existants dans certains territoires (Zones vulnérables, zones sensibles, tronçons liste 2 au titre de la continuité, zones de répartition des eaux …) ne peuvent être retenus comme un motif d'ajustement des résultats.</b> En effet, l'état des lieux est un travail technique de diagnostic qui permet, d'alimenter une éventuelle révision de ces zonages, lorsque nécessaire. </p>
<p><b>La recevabilité des avis émis dépendra du respect de ces consignes, garantes de la co-construction d'un état des lieux 2019 partagé pour élaborer une politique de l'eau dans le bassin, à la fois ambitieuse et réaliste pour la période 2022-2027.</b></p>
