<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.1.1 setup script by Piotr Przybylski <piotrprz@gmail.com>
 * Date: Tue, 16 Dec 2008 09:58:49 +0100
 */
require("../../local.config.inc.php");
/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'localhost';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysql';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = $db_user;
$cfg['Servers'][$i]['password'] = $db_pass;
$cfg['Servers'][$i]['AllowNoPasswordRoot'] = true;
//die("User : ".$db_user." pass : ".$db_pass);
//die("User : ".$cfg['Servers'][$i]['user']." pass : ".$cfg['Servers'][$i]['password']);
/* End of servers configuration */

$cfg['DefaultLang'] = 'fr-latin1';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';

?>