#!/bin/bash
cd /var/www/sie/SIEnouveau/usages-et-pressions/pollution_PCB/basepcb-sediments/admin/local.procedures
#php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_2008.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_2007.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_2006.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_2005.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_2004.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_2003.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_2002.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_2001.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_2000.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1999.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1998.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1997.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1996.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1995.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1994.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1993.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1992.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1991.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1990.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1989.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1988.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1987.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1986.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1985.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1984.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1983.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1982.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1981.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1980.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1979.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1978.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1977.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1976.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1975.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1974.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1973.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1972.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1971.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1970.txt
php -c /etc/php5/apache2/php-cli.ini import_donnees_sediments.php /home/yb/data-sediments/exp_qe_analyse_phy_1969.txt
